name: Build and deploy Docker image to Azure Function

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Tag and Push Docker image to ACR
        env:
          AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        run: |
          docker tag myapp:latest ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/myapp:latest
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/myapp:latest

      - name: Deploy to Azure Function
        env:
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_FUNCTIONAPP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_APP_SERVICE_PLAN: "${{ secrets.AZURE_APP_SERVICE_PLAN }}"
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        run: |
          az functionapp create --name ${{ secrets.AZURE_FUNCTIONAPP_NAME }} \
                                --storage-account ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
                                --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                                --plan "${{ secrets.AZURE_APP_SERVICE_PLAN }}" \
                                --deployment-container-image-name ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/myapp:latest
